"""Train the prototype Gaussian Process on the TS (x_viz[0]) component.

Pipeline:
1. Load state sample points (generated by ``generate_sample_points_per_state``).
2. Join each sample point with its state's ``x_viz`` from
   ``state_coordinates.json`` → target values for the GP.
3. Fit a Matérn 3/2 GP on great-circle distance (length_scale = 0.4 rad).
4. Predict the mean field on a 5° lat/lon grid (≈ 2592 cells).
5. Compute the analytical Jacobian ``(∂μ/∂λ, ∂μ/∂φ)``.
6. Persist a JSON artefact under
   ``packages/civvec_core/basis/continuous_field_ts.json``.

Hyperparameters chosen for the prototype (cf. ``docs/17_continuous_field.md``):

- ``length_scale = 0.4 rad`` ≈ 2540 km on Earth — long enough to interpolate
  smoothly between neighbouring states but short enough to keep regional
  structure.
- ``signal_variance = 1.0`` (data are z-scored before training).
- ``noise_variance = 0.05`` — reflects observation noise; smaller values
  over-fit, larger values smooth the field too aggressively.
"""
from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path

import numpy as np

from apps.basis_builder.paths import BASIS_DIR, STATE_COORDINATES_PATH
from packages.civvec_core.continuous_field.gp import SphericalGaussianProcess
from packages.civvec_core.continuous_field.sample_points import (
    SAMPLE_POINTS_PATH,
    generate_sample_points_per_state,
)

CONTINUOUS_FIELD_TS_PATH = BASIS_DIR / "continuous_field_ts.json"


@dataclass
class TrainedFieldArtefacts:
    grid_longitudes_deg: np.ndarray  # shape (N_lat, N_lon)
    grid_latitudes_deg: np.ndarray
    predicted_mean: np.ndarray
    predicted_variance: np.ndarray
    gradient_longitude: np.ndarray
    gradient_latitude: np.ndarray
    gradient_magnitude: np.ndarray
    n_training_points: int
    length_scale_rad: float
    z_score_mean: float
    z_score_std: float


def _load_sample_points() -> list[dict]:
    if not SAMPLE_POINTS_PATH.exists():
        generate_sample_points_per_state()
    payload = json.loads(SAMPLE_POINTS_PATH.read_text())
    return payload["sample_points"]


def _ts_by_iso3() -> dict[str, float]:
    payload = json.loads(STATE_COORDINATES_PATH.read_text())
    return {
        state["iso3"]: float(state["x_viz"][0])
        for state in payload["states"]
        if state["x_viz"][0] is not None
    }


def train_prototype_field(
    length_scale_rad: float = 0.4,
    noise_variance: float = 0.05,
    grid_step_deg: float = 5.0,
) -> TrainedFieldArtefacts:
    sample_points = _load_sample_points()
    ts_by_iso3 = _ts_by_iso3()

    longitudes_train_rad: list[float] = []
    latitudes_train_rad: list[float] = []
    ts_targets: list[float] = []
    for sample_point in sample_points:
        iso3 = sample_point["iso3"]
        if iso3 not in ts_by_iso3:
            continue
        longitudes_train_rad.append(np.deg2rad(sample_point["longitude_deg"]))
        latitudes_train_rad.append(np.deg2rad(sample_point["latitude_deg"]))
        ts_targets.append(ts_by_iso3[iso3])

    longitudes_train_array = np.array(longitudes_train_rad)
    latitudes_train_array = np.array(latitudes_train_rad)
    ts_targets_array = np.array(ts_targets, dtype=float)

    z_score_mean = float(ts_targets_array.mean())
    z_score_std = float(ts_targets_array.std() + 1e-9)
    ts_targets_normalised = (ts_targets_array - z_score_mean) / z_score_std

    gaussian_process = SphericalGaussianProcess(
        longitudes_train=longitudes_train_array,
        latitudes_train=latitudes_train_array,
        target_values_train=ts_targets_normalised,
        length_scale=length_scale_rad,
        signal_variance=1.0,
        noise_variance=noise_variance,
    ).fit()

    grid_longitudes_deg = np.arange(-180.0, 180.0, grid_step_deg)
    grid_latitudes_deg = np.arange(-90.0, 90.0 + grid_step_deg / 2, grid_step_deg)
    longitudes_grid, latitudes_grid = np.meshgrid(
        grid_longitudes_deg, grid_latitudes_deg
    )

    longitudes_grid_rad = np.deg2rad(longitudes_grid)
    latitudes_grid_rad = np.deg2rad(latitudes_grid)

    predicted_normalised_mean, predicted_normalised_variance = (
        gaussian_process.predict(longitudes_grid_rad, latitudes_grid_rad)
    )
    grad_longitude_normalised, grad_latitude_normalised = gaussian_process.jacobian(
        longitudes_grid_rad, latitudes_grid_rad
    )

    predicted_mean = predicted_normalised_mean * z_score_std + z_score_mean
    predicted_variance = predicted_normalised_variance * z_score_std ** 2
    gradient_longitude = grad_longitude_normalised * z_score_std
    gradient_latitude = grad_latitude_normalised * z_score_std

    metric_factor_per_radian_longitude = np.cos(latitudes_grid_rad)
    polar_mask = np.abs(latitudes_grid) >= 75.0
    safe_metric_factor = np.where(
        polar_mask, np.nan, np.maximum(metric_factor_per_radian_longitude, 1e-3)
    )
    gradient_magnitude = np.sqrt(
        (gradient_longitude / safe_metric_factor) ** 2 + gradient_latitude ** 2
    )

    return TrainedFieldArtefacts(
        grid_longitudes_deg=longitudes_grid,
        grid_latitudes_deg=latitudes_grid,
        predicted_mean=predicted_mean,
        predicted_variance=predicted_variance,
        gradient_longitude=gradient_longitude,
        gradient_latitude=gradient_latitude,
        gradient_magnitude=gradient_magnitude,
        n_training_points=len(ts_targets),
        length_scale_rad=length_scale_rad,
        z_score_mean=z_score_mean,
        z_score_std=z_score_std,
    )


def write_prototype_artefacts(artefacts: TrainedFieldArtefacts) -> Path:
    payload = {
        "_meta": {
            "component": "x_viz[0] — Traditional ↔ Secular-Rational",
            "n_training_points": artefacts.n_training_points,
            "length_scale_rad": artefacts.length_scale_rad,
            "length_scale_km_earth_equivalent": artefacts.length_scale_rad * 6371.0,
            "grid_step_deg": float(
                artefacts.grid_longitudes_deg[0, 1]
                - artefacts.grid_longitudes_deg[0, 0]
            ),
            "z_score_mean": artefacts.z_score_mean,
            "z_score_std": artefacts.z_score_std,
            "schema": "continuous_field_prototype.schema.json",
            "documentation": "docs/17_continuous_field.md",
        },
        "grid": {
            "longitudes_deg": artefacts.grid_longitudes_deg[0, :].tolist(),
            "latitudes_deg": artefacts.grid_latitudes_deg[:, 0].tolist(),
        },
        "predicted_mean_ts": artefacts.predicted_mean.tolist(),
        "predicted_variance_ts": artefacts.predicted_variance.tolist(),
        "gradient_longitude_ts": artefacts.gradient_longitude.tolist(),
        "gradient_latitude_ts": artefacts.gradient_latitude.tolist(),
        "gradient_magnitude_ts": artefacts.gradient_magnitude.tolist(),
    }
    CONTINUOUS_FIELD_TS_PATH.parent.mkdir(parents=True, exist_ok=True)
    CONTINUOUS_FIELD_TS_PATH.write_text(
        json.dumps(payload, indent=2, ensure_ascii=False)
    )
    return CONTINUOUS_FIELD_TS_PATH


if __name__ == "__main__":
    trained = train_prototype_field()
    path = write_prototype_artefacts(trained)
    print(
        f"Wrote {path.name}: {trained.n_training_points} training points → "
        f"{trained.predicted_mean.size} grid cells."
    )
